cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: bootstrap
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2025.6.2
  author_name: Hafida
  bundler: vite
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: none
  description: Hafida_App
  docker_setup: default
  domain_name: localhost:8000
  email: elodie.chassin2000@gmail.com
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: YOUR_GITHUB_USERNAME
  include_static_files: n
  marketing_email_platform: none
  plugins: []
  post_process: n
  project_name: hafida
  project_slug: hafida_001
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_claude: n
  use_ai_rules_cursor: n
  use_ai_rules_junie: n
  use_api_auth: n
  use_api_keys: n
  use_async: n
  use_celery: y
  use_cloud_media_storage: n
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_flowbite: n
  use_health_checks: n
  use_impersonation: n
  use_sentry: n
  use_shadcn: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: n
  use_wagtail: n
